### ISSUE TITLE
WiFi AP problem

### ISSUE THREAD

**Issue by truefriend-cz** [wulfy23/rpi4#1]
Hello, i am using your rpi4.64-snapshot-23909-2.3.97-1-r14869-squs-sys.img.gz but not enabling WiFi in Access Point mode.
After clean flash i going to Wireless and mode "Access Point" aka "Master" after many seconds auto switched to "Clent" mode.

AP is not in list WiFi APs on my device.

On: openwrt-bcm27xx-bcm2711-rpi-4-squashfs-sysupgrade.img.gz
I not have this problem.

Do you can fix?

Factory Reset is not solution.

---

One package - (luci-theme-argon) is new version but not update from CLI (opkg update), or Sotware upgrade.
https://github.com/jerrykuku/luci-theme-argon/releases
(this build have fixed buttons position bugs)

**Comment by wulfy23** [comment]
hello,

wifi issues are known and documented on the README... i've tested the newer argon theme and it was not enough of a change to go through the trouble of porting the current css mods... but you are welcome in both cases to un-install / install whatever works for you... you might need to ask jerrykuku re: the install steps because... it's not build specific and http ipks do work...

good to see someone running the squashfs image...  a pioneer ;)

**Comment by truefriend-cz** [comment]
Hello,

There are no other bugs but this is a crucial feature for me to use your build. Otherwise, all I have to do is use the original one, but there is a lot of work with it and I am not such a skilled worker yet. If you need it, I'll be happy to help with something.
