### ISSUE TITLE
Cannot Flash 7.1.31-3

### ISSUE THREAD

**Issue by JAAlperin** [wulfy23/rpi4#21]
Red "Flash" link does not complete. Manual "Flash Image" results in "Image Check Failed."  Please see screen shots.

![Screen Shot 2022-06-27 at 7 49 53 AM](https://user-images.githubusercontent.com/26283546/175935504-a2f4fbc8-ac5c-4f6c-b1d2-c3c62ded2a70.jpg)
![Screen Shot 2022-06-27 at 7 48 20 AM](https://user-images.githubusercontent.com/26283546/175935434-af86a1c1-3554-4cd6-9ca5-143fbbfadd84.jpg)
![Screen Shot 2022-06-27 at 7 48 56 AM](https://user-images.githubusercontent.com/26283546/175935505-e70cb20a-ab5f-445e-82ee-3671877e9f5b.jpg)

**Comment by malikshi** [comment]
Try upgrade through terminal
I had problem with curl yesterday so i flashed same version to fix it.
`sysupgrade -F /path-to-file`
Recommended to save firmware file in /tmp

**Comment by anipad** [comment]
Does manual `sysupgrade -F` keep settings and configuration in this build without `-f`?

**Comment by wulfy23** [comment]
Thanks for the screenshots and help Malikshi something seems to have changed in the image validation code so until I can take a look as above, sysupgrade -F /tmp/sys.img.gz will flash... adding -R will get you the built in package restore features...

The build pretty much always keeps settings unless you issue -n but this is largely untested.

**Comment by malikshi** [comment]
Thanks you for further explanation

**Comment by wulfy23** [comment]
Seems certificate i'd been using expired. We were due for a rotation anyway... thanks again for making me aware of the issue...

I'll resolve this weekend...

**Comment by JAAlperin** [comment]
Thank you for your generous help.

Regards,

Jeff Alperin
H: 561-666-7789
C: 561-797-9876

**Comment by zer0fl0w** [comment]
you are still on 'stable' channel...

put it to:
UPGRADEsFLAVOUR="current"

**Comment by netmask69** [comment]
thanks for your suggestion, solved.

**Comment by wulfy23** [comment]
seems sorted... re-reading the thread it's possible there is a hidden bug (or I put a 'release' image in stable for a while and that messed it up) that shifted your FLAVOUR to stable...

for the record rather than dig too much now. my code should not change your FLAVOUR... except in the case of firstboot, where if you start with a 'release/stable' image, then 'current' is changed to stable afair... all upgrade after this should leave your setting untouched unless you changed it manually.

you will however as you've noticed, be notified if your flavour is 'current' and you install a stable build... i.e. 'you are running 2.x.x but there is newer 7.x.x' its simply the update system checking where it was told to look.

thanks for the help also... closing re-open if needed.

**Comment by JAAlperin** [comment]
I’m set for now.  Thanks for everything you do!

Regards,

Jeff Alperin
H: 561-666-7789
C: 561-797-9876

**Comment by JAAlperin** [comment]
Sorry.  I've lost track of this.  New version now available, but flash link is gone.  How is this accomplished now?
