### ISSUE TITLE
dscpclassify doesnt seem to work with wulfy build

### ISSUE THREAD

**Issue by rspierz** [wulfy23/rpi4#36]
Hey Wulfy23,

I was trying to get dscpclassfiy working on your build. I  am not able to get trafic to follow into the other tins (other then best effort) when configuring cake sqm layer_cake diffserv4. Are you able to shed any light why this might be not able to work correctly?

**Comment by wulfy23** [comment]
glad to hear that... I think I might have left some stale stuff in the readme or legacy scripts around maybe... but anyway just in case someone reads this issue for reference:

**dscpclassfiy** was a set of scripts afair derived from that long running thread on the forum I forget the name... 

that later morphed into some of that stuff weaved into '**...rpi4....qos**' who's original developer and creator is also documented somewhere...

like another issue here, if they work great, but they were written approx 15?+ months ago, so also probably need a rewrite / retest... for reference... I use them and for sure they were beneficial up until around 3 months ago... but since then I've seen a change which is not 'all bad' but definitely indicates that there might be better options out there / minor issues etc. etc.

this would be another cantidate for 'opening up' but it's so messy that i'd probably start fresh (with master nft only version) or seek third party alternative...
