### ISSUE TITLE
USB Ethernet - over charging port

### ISSUE THREAD

**Issue by unclehowell** [wulfy23/rpi4#4]
You think you could see if you can get USB Ethernet working with OpenWRT on Pi4 e.g. SSH over the power USB (when connect to a machine). That would be awesome

**Comment by wulfy23** [comment]
it already works... it is quite complicated tho' due to cable specifics and the hardware wiring on the device sadly... to tweaking the build to enable it out of the box would imply advanced knowledge/hardware of/for this by users most of whom wont have...

like all things with the build tho'... propose the necessary code / package changes on the forum thread and if 3 or more people really want / will use this feature i'd be happy to add a few specific configs or setup automation for this :)

otherwise just install any packages that are needed, make sure you have the right cables and configure your settings...

peace

**Comment by unclehowell** [comment]
peace

**Comment by wulfy23** [comment]
fwiw... i've just enabled this by default ( driver side )
and while its really not worth the hassle due to the
complicated and risky cable complications...

-requires reboot after firstboot

-you still need /etc/config/network i.e.;

config interface 'gether'
	option proto 'static'
	option ipaddr '10.11.12.3'
	option netmask '255.255.255.0'
	option macaddr 'CC:DD:32:77:DD:65'
	option device 'usb0'

will get you setup on any (newer) build

**Comment by wulfy23** [comment]
i've just disabled this by default... not a good idea... but there are some more drivers and most of the setup logic ready to go for anyone with the need... (and skills to handle potential fallout)
