### ISSUE TITLE
statistics app broke

### ISSUE THREAD

**Issue by kpoman** [wulfy23/rpi4#42]
I am running this: rpi-4_snapshot_7.3.9-5_r23344_extra
I installed luci-app-statistics (luci-app-statistics - git-23.151.54709-c9c3959) ... this should show a new menu with submenus in Luci (statistics/graphs and statistics/collectd) but all is missing. If trying to access with the url http://192.168.10.5/cgi-bin/luci/admin/statistics, I get this error:

```
Error
Unhandled exception during request dispatching
Internal node resolve error
In resolve_page(), file /usr/share/ucode/luci/dispatcher.uc, line 668, byte 45:
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:897:41)
  called from anonymous function (/www/cgi-bin/luci:39:12)

 `        assert(node, "Internal node resolve error");`
  Near here ----------------------------------------^
```

**Comment by wulfy23** [comment]
Hello there,

Apologies for the late reply. FWIW I've run that version and used statistics and not seen that error. Having said that snapshot since march had alot of changes to the UI so can't rule out some anomaly.

2 things to be aware of...

1) during upgrade, be patient for that 3-5 mins and let the system do it's thing on firstboot

2) possible http / https autoredirect issues i've seen on and off with OpenWrt, with issues like this, reboot the router, use a different browser (full cache flush) and or enable / use https / http to see if it makes a difference...

Failing that you could re-install the app ( probably --force-maintainer )...


Cheers
(reopen if shows on any stable / alternate build)
